#!/bin/bash
# RPM or Debian script (assumes that libs are in /usr/share/jajuk/lib and jajuk.jar in /usr/share/java)

#JVM arguments used by Jajuk. It's important  to notice that some of this tuning is useful only when using Java player (when mplayer is not available)
# * -client : Use the client JVM, optimized for single user usage [Don't change this setting]
# * -Xms : Initial Heap (total JVM reserved memory) size. We set it to a pretty large value because it requires resources to expand heap size.
# * -Xmx: Maximal Heap size. We set a large size because Out Of Memory errors make the application crash. In some rare cases, very large collection (>200Gb) users could increase this setting (see Performance section in the manual) [Change this setting only if you have very large collection, do not reduce it]
# * -Xverify:none : quicker startup, no bytecode check
JAVA_OPTIONS="-client -Xms30M -Xmx2G -Xverify:none"

#Jajuk options
JAJUK_OPTIONS="@TEST_FLAG_REPLACED_BY_ANT@"

## Check 32- or 64-bit system
if [ "`uname -m`" = "x86_64" ]; then
	ARCHLIB=lib64
else
    ARCHLIB=lib32
fi

##let's finally start Jajuk displaying the command:
set -o xtrace
java $JAVA_OPTIONS -Djava.library.path=/usr/share/jajuk/$ARCHLIB -jar /usr/share/java/jajuk.jar $JAJUK_OPTIONS
