/*
 *  Jajuk
 *  Copyright (C) The Jajuk Team
 *  http://jajuk.info
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *  
 */
package org.jajuk.util;

/**
 * List of Jajuk icons.
 */
public enum JajukIcons {
  NO_COVER, NONE, NO_COVER_50X50, NO_COVER_100X100, NO_COVER_150X150, NO_COVER_200X200, NO_COVER_250X250, NO_COVER_300X300, LOGO,  COVER_16X16, LOGO_FRAME, REPEAT, REPEAT_ALL, SHUFFLE, CONTINUE, INTRO, KARAOKE, SHUFFLE_GLOBAL, SHUFFLE_GLOBAL_16X16, BESTOF, BESTOF_16X16, MUTED, VOLUME_LEVEL1, VOLUME_LEVEL2, VOLUME_LEVEL3, WEBRADIO, NOVELTIES, NOVELTIES_16X16, PLAYER_NEXT_SMALL, SAVE_AS, PLAYER_PREVIOUS_SMALL, PLAYER_PREVIOUS, PLAYER_PREVIOUS_BIG, PLAYER_NEXT, PLAYER_NEXT_BIG, INC_RATING, REW, REW_16X16, PLAYER_PLAY, PLAY_16X16, PLAYER_PAUSE, PAUSE_16X16, PLAYER_STOP, STOP_16X16, FWD, FWD_16X16, VOLUME, CLOSE, SLIM_WINDOW, FULL_SCREEN, STOP_AFTER, INFO, BOOKMARK_FOLDERS, PERSPECTIVE_SIMPLE, PERSPECTIVE_PHYSICAL, PERSPECTIVE_LOGICAL, PERSPECTIVE_STATISTICS, PERSPECTIVE_CONFIGURATION, PERSPECTIVE_PLAYER, PERSPECTIVE_CATALOG, PERSPECTIVE_PLAYLISTS, PERSPECTIVE_INFORMATION, OPEN_FILE, EXIT, NEW, SEARCH, DELETE, PROPERTIES, VOID, CONFIGURATION, MOUNT, UPDATE_MANAGER, UNMOUNT, TRACES, TEST, REORGANIZE, REFRESH, RESTORE_ALL_VIEWS, SYNCHRO, DEVICE_NEW, DEVICE_CD_MOUNTED, DEVICE_CD_UNMOUNTED, DEVICE_EXT_DD_MOUNTED, DEVICE_EXT_DD_UNMOUNTED, DEVICE_DIRECTORY_MOUNTED, DEVICE_DIRECTORY_UNMOUNTED, DEVICE_PLAYER_MOUNTED, DEVICE_PLAYER_UNMOUNTED, DEVICE_NETWORK_DRIVE_MOUNTED, DEVICE_NETWORK_DRIVE_UNMOUNTED, DEVICE_CD_MOUNTED_SMALL, DEVICE_CD_UNMOUNTED_SMALL, DEVICE_EXT_DD_MOUNTED_SMALL, DEVICE_EXT_DD_UNMOUNTED_SMALL, DEVICE_NETWORK_DRIVE_MOUNTED_SMALL, DEVICE_NETWORK_DRIVE_UNMOUNTED_SMALL, DEVICE_DIRECTORY_MOUNTED_SMALL, DEVICE_DIRECTORY_UNMOUNTED_SMALL, DEVICE_PLAYER_MOUNTED_SMALL, DEVICE_PLAYER_UNMOUNTED_SMALL, OK, OK_SMALL, KO, TRACK, DIRECTORY_SYNCHRO, DIRECTORY_DESYNCHRO, PLAYLIST_FILE, GENRE, EMPTY, ARTIST, ALBUM, ALBUM_ARTIST, YEAR, APPLY_FILTER, DISCOVERY_DATE, CLEAR_FILTER, ADVANCED_FILTER, PLAYLIST_NEW, PLAYLIST_NEW_SMALL, PLAYLIST_BOOKMARK, PLAYLIST_BOOKMARK_SMALL, PLAYLIST_BESTOF, PLAYLIST_NOVELTIES, RUN, ADD, REMOVE, UP, DOWN, ADD_SHUFFLE, CLEAR, SAVE, EXT_DRIVE, DEFAULT_COVER, FINISH_ALBUM, FINISH_ALBUM_16X16, NET_SEARCH, TRACK_FIFO_PLANNED, TRACK_FIFO_NORM, TRACK_FIFO_REPEAT, WIZARD, TYPE_MP3, TYPE_MP2, TYPE_OGG, TYPE_AU, TYPE_AIFF, TYPE_FLAC, TYPE_MPC, TYPE_WMA, TYPE_APE, TYPE_AAC, TYPE_WAV, TYPE_RAM, NO_EDIT, EDIT, UNKNOWN, TIP, TIP_SMALL, OPEN_DIR, STAR_0, STAR_1, STAR_2, STAR_3, STAR_4, DROP_DOWN_32X32, DROP_DOWN_16X16, DIGITAL_DJ, DIGITAL_DJ_16X16, WEBRADIO_16X16, LIST, CDDB, PLAY_TABLE, DEFAULTS, DEFAULTS_BIG, ACCURACY_LOW, ACCURACY_MEDIUM, ACCURACY_HIGH, REPORT, PUSH, COPY, CUT, PASTE, LAUNCH, HISTORY, POPUP, ALARM, BAN, PREFERENCE_HATE, PREFERENCE_POOR, PREFERENCE_AVERAGE, PREFERENCE_LIKE, PREFERENCE_LOVE, PREFERENCE_ADORE, PREFERENCE_UNSET, UNBAN, PREPARE_PARTY,
  /** Larger icon for Prepare Party Wizard. */
  PREPARE_PARTY_32X32, COPY_TO_CLIPBOARD, OPEN_EXPLORER, AMBIENCE, PLAYER_FORWARD_BIG, PLAYER_STOP_BIG, PLAYER_PLAY_BIG, PLAYER_PAUSE_BIG, PLAYER_REWIND_BIG, AUTOSCROLL,
  /** Tree/table synchronization icon. */
  TREE_TABLE_SYNC,
  /** Money. */
  DONATE,
  /** Disc number. */
  DISC_NUMBER
}
