<component name="libraryTable">
  <library name="build">
    <CLASSES>
      <root url="jar://$PROJECT_DIR$/lib/build/apiguardian-api-1.1.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/byte-buddy-1.17.5.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/byte-buddy-agent-1.17.5.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/jarbundler-2.4.0.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/jdeb-1.5.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/junit-jupiter-api-5.12.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/junit-jupiter-engine-5.12.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/junit-platform-commons-1.12.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/junit-platform-engine-1.12.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/junit-platform-launcher-1.12.2.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/mockito-core-5.18.0.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/mockito-junit-jupiter-5.18.0.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/nsisant-1.3.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/objenesis-3.3.jar!/" />
      <root url="jar://$PROJECT_DIR$/lib/build/opentest4j-1.3.0.jar!/" />
    </CLASSES>
    <JAVADOC />
    <SOURCES />
  </library>
</component>
