#!/bin/sh
#Jajuk launching script for unix in RPM install, assumes javaw program is in the PATH env. variable

#Go in the right environment directory
cd /usr/lib/jajuk/bin

#Launch jajuk
java -client -Xms25M -Xmx512M -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -Dapple.laf.useScreenMenuBar=true -jar jajuk.jar -notaskbar TEST_FLAG_REPLACED_BY_ANT
